In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import pickle

In [2]:
# Load original data set
data_path = '/Volumes/Transcend/metis_data/Turnstile_Usage_Data__2018.csv'
df_orig = pd.read_csv(data_path )
df_orig

,C/A,Unit,SCP,Station,Line Name,Division,Date,Time,Description,Entries,Exits
0,A033,R170,02-00-00,14 ST-UNION SQ,LNQR456W,BMT,12/28/2018,00:00:00,REGULAR,2056268,5177036
1,A033,R170,02-06-01,14 ST-UNION SQ,LNQR456W,BMT,12/28/2018,00:00:00,REGULAR,70294362,20274025
2,A033,R170,02-00-02,14 ST-UNION SQ,LNQR456W,BMT,12/28/2018,00:00:00,REGULAR,14197229,13704110
3,A033,R170,02-00-01,14 ST-UNION SQ,LNQR456W,BMT,12/28/2018,00:00:00,REGULAR,1806541,2182381
4,A033,R170,02-00-05,14 ST-UNION SQ,LNQR456W,BMT,12/28/2018,00:00:00,REGULAR,15598097,6250334
5,A033,R170,02-00-03,14 ST-UNION SQ,LNQR456W,BMT,12/28/2018,00:00:00,REGULAR,6069026,7074661
6,A033,R170,02-00-04,14 ST-UNION SQ,LNQR456W,BMT,12/28/2018,00:00:00,REGULAR,4927946,3748371
7,A033,R170,02-00-01,14 ST-UNION SQ,LNQR456W,BMT,12/28/2018,00:00:00,REGULAR,1806541,2182381
8,A033,R170,02-06-00,14 ST-UNION SQ,LNQR456W,BMT,12/28/2018,00:00:00,REGULAR,694109,207786
9,A033,R170,02-06-01,14 ST-UNION SQ,LNQR456W,BMT,12/28/2018,00:00:00,REGULAR,70294362,20274025
10,A033,R170,02-00-00,14 ST-UNION SQ,LNQR456W,BMT,12/28/2018,00:00:00,REGULAR,2056268,5177036
11,A033,R170,02-00-04,14 ST-UNION SQ,LNQR456W,BMT,12/28/2018,00:00:00,REGULAR,4927946,3748371
12,A033,R170,02-00-03,14 ST-UNION SQ,LNQR456W,BMT,12/28/2018,00:00:00,REGULAR,6069026,7074661
13,A033,R170,02-06-00,14 ST-UNION SQ,LNQR456W,BMT,12/28/2018,00:00:00,REGULAR,694109,207786
14,A033,R170,02-00-02,14 ST-UNION SQ,LNQR456W,BMT,12/28/2018,00:00:00,REGULAR,14197229,13704110
15,A033,R170,02-00-05,14 ST-UNION SQ,LNQR456W,BMT,12/28/2018,00:00:00,REGULAR,15598097,6250334
16,A034,R170,03-00-00,14 ST-UNION SQ,LNQR456W,BMT,12/28/2018,00:00:00,REGULAR,1923632,14843362
17,A034,R170,03-00-02,14 ST-UNION SQ,LNQR456W,BMT,12/28/2018,00:00:00,REGULAR,3687618,2644410
18,A034,R170,03-00-00,14 ST-UNION SQ,LNQR456W,BMT,12/28/2018,00:00:00,REGULAR,1923632,14843362
19,A034,R170,03-06-00,14 ST-UNION SQ,LNQR456W,BMT,12/28/2018,00:00:00,REGULAR,68007701,17207000
20,A034,R170,03-00-01,14 ST-UNION SQ,LNQR456W,BMT,12/28/2018,00:00:00,REGULAR,499334,1229391
21,A034,R170,03-06-00,14 ST-UNION SQ,LNQR456W,BMT,12/28/2018,00:00:00,REGULAR,68007701,17207000
22,A034,R170,03-06-02,14 ST-UNION SQ,LNQR456W,BMT,12/28/2018,00:00:00,REGULAR,202795687,85357013
23,A034,R170,03-03-00,14 ST-UNION SQ,LNQR456W,BMT,12/28/2018,00:00:00,REGULAR,3298435,8319358
24,A034,R170,03-06-02,14 ST-UNION SQ,LNQR456W,BMT,12/28/2018,00:00:00,REGULAR,202795687,85357013
25,A034,R170,03-00-01,14 ST-UNION SQ,LNQR456W,BMT,12/28/2018,00:00:00,REGULAR,499334,1229391
26,A034,R170,03-06-01,14 ST-UNION SQ,LNQR456W,BMT,12/28/2018,00:00:00,REGULAR,3965537,2697302
27,A034,R170,03-00-02,14 ST-UNION SQ,LNQR456W,BMT,12/28/2018,00:00:00,REGULAR,3687618,2644410
28,A034,R170,03-03-01,14 ST-UNION SQ,LNQR456W,BMT,12/28/2018,00:00:00,REGULAR,5569358,3334854
29,A034,R170,03-03-02,14 ST-UNION SQ,LNQR456W,BMT,12/28/2018,00:00:00,REGULAR,11499477,1255112
...,...,...,...,...,...,...,...,...,...,...,...
10111441,PTH17,R541,01-00-03,THIRTY THIRD ST,1,PTH,12/23/2017,23:34:05,REGULAR,0,624646
10111442,PTH19,R549,02-02-04,NEWARK C,1,PTH,12/23/2017,23:34:44,REGULAR,11458,1207
10111443,PTH07,R550,00-01-00,CITY / BUS,1,PTH,12/23/2017,23:35:17,REGULAR,705646,316016
10111444,PTH07,R550,00-01-03,CITY / BUS,1,PTH,12/23/2017,23:35:38,REGULAR,22560,7426
10111445,PTH20,R549,03-01-04,NEWARK HM HE,1,PTH,12/23/2017,23:36:26,REGULAR,20148,508771
10111446,PTH04,R551,00-01-04,GROVE STREET,1,PTH,12/23/2017,23:37:50,REGULAR,12267,27879
10111447,PTH03,R552,00-00-0A,JOURNAL SQUARE,1,PTH,12/23/2017,23:38:27,REGULAR,63,3552289
10111448,PTH20,R549,03-01-08,NEWARK HM HE,1,PTH,12/23/2017,23:39:21,REGULAR,40,3930
10111449,PTH04,R551,00-01-02,GROVE STREET,1,PTH,12/23/2017,23:40:50,REGULAR,294205,400278
10111450,PTH22,R540,00-04-07,PATH NEW WTC,1,PTH,12/23/2017,23:42:06,REGULAR,10819,23659
10111451,PTH05,R543,00-00-03,EXCHANGE PLACE,1,PTH,12/23/2017,23:43:25,REGULAR,592989,152535
10111452,PTH09,R548,00-00-00,CHRISTOPHER ST,1,PTH,12/23/2017,23:43:39,REGULAR,471951,756777
10111453,PTH19,R549,02-01-06,NEWARK C,1,PTH,12/23/2017,23:43:45,REGULAR,71881,8153
10111454,PTH05,R543,00-04-02,EXCHANGE PLACE,1,PTH,12/23/2017,23:44:33,REGULAR,151,44
10111455,PTH04,R551,00-04-06,GROVE STREET,1,PTH,12/23/2017,23:44:46,REGULAR,33382,20603
10111456,PTH04,R551,00-00-00,GROVE STREET,1,PTH,12/23/2017,23:46:15,REGULAR,151201,46323
10111457,PTH03,R552,00-00-03,JOURNAL SQUARE,1,PTH,12/23/2017,23:47:27,REGULAR,82025,24232
10111458,PTH10,R547,00-00-04,9TH STREET,1,PTH,12/23/2017,23:48:09,REGULAR,133500,790410
10111459,PTH11,R545,00-00-03,14TH STREET,1,PTH,12/23/2017,23:48:51,REGULAR,4271,195
10111460,PTH02,R544,00-00-00,HARRISON,1,PTH,12/23/2017,23:48:59,REGULAR,29679,7207
10111461,PTH05,R543,00-00-00,EXCHANGE PLACE,1,PTH,12/23/2017,23:49:08,REGULAR,711590,47759
10111462,PTH17,R541,01-01-03,THIRTY THIRD ST,1,PTH,12/23/2017,23:49:20,REGULAR,248386,113198
10111463,PTH06,R546,00-00-02,PAVONIA/NEWPORT,1,PTH,12/23/2017,23:51:49,REGULAR,3021,866
10111464,PTH16,R550,01-00-00,LACKAWANNA,1,PTH,12/23/2017,23:52:01,REGULAR,14659,51404
10111465,PTH05,R543,00-01-07,EXCHANGE PLACE,1,PTH,12/23/2017,23:54:18,REGULAR,14057,2311
10111466,PTH22,R540,00-01-00,PATH NEW WTC,1,PTH,12/23/2017,23:54:36,REGULAR,99297,24068
10111467,PTH06,R546,00-00-03,PAVONIA/NEWPORT,1,PTH,12/23/2017,23:55:47,REGULAR,4417,2955
10111468,PTH07,R550,00-02-02,CITY / BUS,1,PTH,12/23/2017,23:58:16,REGULAR,12121,56099
10111469,PTH06,R546,00-00-06,PAVONIA/NEWPORT,1,PTH,12/23/2017,23:58:34,REGULAR,174521,680268
10111470,PTH03,R552,00-00-07,JOURNAL SQUARE,1,PTH,12/23/2017,23:59:34,REGULAR,4020504,1291262

In [3]:
import re
df = df_orig.copy()
# Truncating data set
# mask = df_orig['Date'].map(lambda x: re.search('(05|06)/.+/(2017|2018)', x) != None)
# df = df_orig[mask]

# Adding new column 'Full Time' with data and time information
df['Full Time']=pd.to_datetime(df['Date'] + ' ' + df['Time'], format = '%m/%d/%Y %H:%M:%S')

# Delete whitespace
df = df.rename(columns=lambda x: x.strip())

df

,C/A,Unit,SCP,Station,Line Name,Division,Date,Time,Description,Entries,Exits,Full Time
0,A033,R170,02-00-00,14 ST-UNION SQ,LNQR456W,BMT,12/28/2018,00:00:00,REGULAR,2056268,5177036,2018-12-28 00:00:00
1,A033,R170,02-06-01,14 ST-UNION SQ,LNQR456W,BMT,12/28/2018,00:00:00,REGULAR,70294362,20274025,2018-12-28 00:00:00
2,A033,R170,02-00-02,14 ST-UNION SQ,LNQR456W,BMT,12/28/2018,00:00:00,REGULAR,14197229,13704110,2018-12-28 00:00:00
3,A033,R170,02-00-01,14 ST-UNION SQ,LNQR456W,BMT,12/28/2018,00:00:00,REGULAR,1806541,2182381,2018-12-28 00:00:00
4,A033,R170,02-00-05,14 ST-UNION SQ,LNQR456W,BMT,12/28/2018,00:00:00,REGULAR,15598097,6250334,2018-12-28 00:00:00
5,A033,R170,02-00-03,14 ST-UNION SQ,LNQR456W,BMT,12/28/2018,00:00:00,REGULAR,6069026,7074661,2018-12-28 00:00:00
6,A033,R170,02-00-04,14 ST-UNION SQ,LNQR456W,BMT,12/28/2018,00:00:00,REGULAR,4927946,3748371,2018-12-28 00:00:00
7,A033,R170,02-00-01,14 ST-UNION SQ,LNQR456W,BMT,12/28/2018,00:00:00,REGULAR,1806541,2182381,2018-12-28 00:00:00
8,A033,R170,02-06-00,14 ST-UNION SQ,LNQR456W,BMT,12/28/2018,00:00:00,REGULAR,694109,207786,2018-12-28 00:00:00
9,A033,R170,02-06-01,14 ST-UNION SQ,LNQR456W,BMT,12/28/2018,00:00:00,REGULAR,70294362,20274025,2018-12-28 00:00:00
10,A033,R170,02-00-00,14 ST-UNION SQ,LNQR456W,BMT,12/28/2018,00:00:00,REGULAR,2056268,5177036,2018-12-28 00:00:00
11,A033,R170,02-00-04,14 ST-UNION SQ,LNQR456W,BMT,12/28/2018,00:00:00,REGULAR,4927946,3748371,2018-12-28 00:00:00
12,A033,R170,02-00-03,14 ST-UNION SQ,LNQR456W,BMT,12/28/2018,00:00:00,REGULAR,6069026,7074661,2018-12-28 00:00:00
13,A033,R170,02-06-00,14 ST-UNION SQ,LNQR456W,BMT,12/28/2018,00:00:00,REGULAR,694109,207786,2018-12-28 00:00:00
14,A033,R170,02-00-02,14 ST-UNION SQ,LNQR456W,BMT,12/28/2018,00:00:00,REGULAR,14197229,13704110,2018-12-28 00:00:00
15,A033,R170,02-00-05,14 ST-UNION SQ,LNQR456W,BMT,12/28/2018,00:00:00,REGULAR,15598097,6250334,2018-12-28 00:00:00
16,A034,R170,03-00-00,14 ST-UNION SQ,LNQR456W,BMT,12/28/2018,00:00:00,REGULAR,1923632,14843362,2018-12-28 00:00:00
17,A034,R170,03-00-02,14 ST-UNION SQ,LNQR456W,BMT,12/28/2018,00:00:00,REGULAR,3687618,2644410,2018-12-28 00:00:00
18,A034,R170,03-00-00,14 ST-UNION SQ,LNQR456W,BMT,12/28/2018,00:00:00,REGULAR,1923632,14843362,2018-12-28 00:00:00
19,A034,R170,03-06-00,14 ST-UNION SQ,LNQR456W,BMT,12/28/2018,00:00:00,REGULAR,68007701,17207000,2018-12-28 00:00:00
20,A034,R170,03-00-01,14 ST-UNION SQ,LNQR456W,BMT,12/28/2018,00:00:00,REGULAR,499334,1229391,2018-12-28 00:00:00
21,A034,R170,03-06-00,14 ST-UNION SQ,LNQR456W,BMT,12/28/2018,00:00:00,REGULAR,68007701,17207000,2018-12-28 00:00:00
22,A034,R170,03-06-02,14 ST-UNION SQ,LNQR456W,BMT,12/28/2018,00:00:00,REGULAR,202795687,85357013,2018-12-28 00:00:00
23,A034,R170,03-03-00,14 ST-UNION SQ,LNQR456W,BMT,12/28/2018,00:00:00,REGULAR,3298435,8319358,2018-12-28 00:00:00
24,A034,R170,03-06-02,14 ST-UNION SQ,LNQR456W,BMT,12/28/2018,00:00:00,REGULAR,202795687,85357013,2018-12-28 00:00:00
25,A034,R170,03-00-01,14 ST-UNION SQ,LNQR456W,BMT,12/28/2018,00:00:00,REGULAR,499334,1229391,2018-12-28 00:00:00
26,A034,R170,03-06-01,14 ST-UNION SQ,LNQR456W,BMT,12/28/2018,00:00:00,REGULAR,3965537,2697302,2018-12-28 00:00:00
27,A034,R170,03-00-02,14 ST-UNION SQ,LNQR456W,BMT,12/28/2018,00:00:00,REGULAR,3687618,2644410,2018-12-28 00:00:00
28,A034,R170,03-03-01,14 ST-UNION SQ,LNQR456W,BMT,12/28/2018,00:00:00,REGULAR,5569358,3334854,2018-12-28 00:00:00
29,A034,R170,03-03-02,14 ST-UNION SQ,LNQR456W,BMT,12/28/2018,00:00:00,REGULAR,11499477,1255112,2018-12-28 00:00:00
...,...,...,...,...,...,...,...,...,...,...,...,...
10111441,PTH17,R541,01-00-03,THIRTY THIRD ST,1,PTH,12/23/2017,23:34:05,REGULAR,0,624646,2017-12-23 23:34:05
10111442,PTH19,R549,02-02-04,NEWARK C,1,PTH,12/23/2017,23:34:44,REGULAR,11458,1207,2017-12-23 23:34:44
10111443,PTH07,R550,00-01-00,CITY / BUS,1,PTH,12/23/2017,23:35:17,REGULAR,705646,316016,2017-12-23 23:35:17
10111444,PTH07,R550,00-01-03,CITY / BUS,1,PTH,12/23/2017,23:35:38,REGULAR,22560,7426,2017-12-23 23:35:38
10111445,PTH20,R549,03-01-04,NEWARK HM HE,1,PTH,12/23/2017,23:36:26,REGULAR,20148,508771,2017-12-23 23:36:26
10111446,PTH04,R551,00-01-04,GROVE STREET,1,PTH,12/23/2017,23:37:50,REGULAR,12267,27879,2017-12-23 23:37:50
10111447,PTH03,R552,00-00-0A,JOURNAL SQUARE,1,PTH,12/23/2017,23:38:27,REGULAR,63,3552289,2017-12-23 23:38:27
10111448,PTH20,R549,03-01-08,NEWARK HM HE,1,PTH,12/23/2017,23:39:21,REGULAR,40,3930,2017-12-23 23:39:21
10111449,PTH04,R551,00-01-02,GROVE STREET,1,PTH,12/23/2017,23:40:50,REGULAR,294205,400278,2017-12-23 23:40:50
10111450,PTH22,R540,00-04-07,PATH NEW WTC,1,PTH,12/23/2017,23:42:06,REGULAR,10819,23659,2017-12-23 23:42:06
10111451,PTH05,R543,00-00-03,EXCHANGE PLACE,1,PTH,12/23/2017,23:43:25,REGULAR,592989,152535,2017-12-23 23:43:25
10111452,PTH09,R548,00-00-00,CHRISTOPHER ST,1,PTH,12/23/2017,23:43:39,REGULAR,471951,756777,2017-12-23 23:43:39
10111453,PTH19,R549,02-01-06,NEWARK C,1,PTH,12/23/2017,23:43:45,REGULAR,71881,8153,2017-12-23 23:43:45
10111454,PTH05,R543,00-04-02,EXCHANGE PLACE,1,PTH,12/23/2017,23:44:33,REGULAR,151,44,2017-12-23 23:44:33
10111455,PTH04,R551,00-04-06,GROVE STREET,1,PTH,12/23/2017,23:44:46,REGULAR,33382,20603,2017-12-23 23:44:46
10111456,PTH04,R551,00-00-00,GROVE STREET,1,PTH,12/23/2017,23:46:15,REGULAR,151201,46323,2017-12-23 23:46:15
10111457,PTH03,R552,00-00-03,JOURNAL SQUARE,1,PTH,12/23/2017,23:47:27,REGULAR,82025,24232,2017-12-23 23:47:27
10111458,PTH10,R547,00-00-04,9TH STREET,1,PTH,12/23/2017,23:48:09,REGULAR,133500,790410,2017-12-23 23:48:09
10111459,PTH11,R545,00-00-03,14TH STREET,1,PTH,12/23/2017,23:48:51,REGULAR,4271,195,2017-12-23 23:48:51
10111460,PTH02,R544,00-00-00,HARRISON,1,PTH,12/23/2017,23:48:59,REGULAR,29679,7207,2017-12-23 23:48:59
10111461,PTH05,R543,00-00-00,EXCHANGE PLACE,1,PTH,12/23/2017,23:49:08,REGULAR,711590,47759,2017-12-23 23:49:08
10111462,PTH17,R541,01-01-03,THIRTY THIRD ST,1,PTH,12/23/2017,23:49:20,REGULAR,248386,113198,2017-12-23 23:49:20
10111463,PTH06,R546,00-00-02,PAVONIA/NEWPORT,1,PTH,12/23/2017,23:51:49,REGULAR,3021,866,2017-12-23 23:51:49
10111464,PTH16,R550,01-00-00,LACKAWANNA,1,PTH,12/23/2017,23:52:01,REGULAR,14659,51404,2017-12-23 23:52:01
10111465,PTH05,R543,00-01-07,EXCHANGE PLACE,1,PTH,12/23/2017,23:54:18,REGULAR,14057,2311,2017-12-23 23:54:18
10111466,PTH22,R540,00-01-00,PATH NEW WTC,1,PTH,12/23/2017,23:54:36,REGULAR,99297,24068,2017-12-23 23:54:36
10111467,PTH06,R546,00-00-03,PAVONIA/NEWPORT,1,PTH,12/23/2017,23:55:47,REGULAR,4417,2955,2017-12-23 23:55:47
10111468,PTH07,R550,00-02-02,CITY / BUS,1,PTH,12/23/2017,23:58:16,REGULAR,12121,56099,2017-12-23 23:58:16
10111469,PTH06,R546,00-00-06,PAVONIA/NEWPORT,1,PTH,12/23/2017,23:58:34,REGULAR,174521,680268,2017-12-23 23:58:34
10111470,PTH03,R552,00-00-07,JOURNAL SQUARE,1,PTH,12/23/2017,23:59:34,REGULAR,4020504,1291262,2017-12-23 23:59:34

In [ ]:
print(df['Full Time'].min(),df['Full Time'].max())

In [5]:
# Create a group dataframe for each individual turnstile
gdf = df.groupby(['Station','Line Name','SCP','C/A','Unit'])

print('Number of turnstiles : ',len(gdf))

Number of turnstiles :  4947

In [31]:
# Pick out times to query
times_query = pd.date_range('2017-12-23 00:00:00','2018-12-28 00:00:00',freq = 'H')
times_query

DatetimeIndex(['2017-12-23 00:00:00', '2017-12-23 01:00:00',
               '2017-12-23 02:00:00', '2017-12-23 03:00:00',
               '2017-12-23 04:00:00', '2017-12-23 05:00:00',
               '2017-12-23 06:00:00', '2017-12-23 07:00:00',
               '2017-12-23 08:00:00', '2017-12-23 09:00:00',
               ...
               '2018-12-27 15:00:00', '2018-12-27 16:00:00',
               '2018-12-27 17:00:00', '2018-12-27 18:00:00',
               '2018-12-27 19:00:00', '2018-12-27 20:00:00',
               '2018-12-27 21:00:00', '2018-12-27 22:00:00',
               '2018-12-27 23:00:00', '2018-12-28 00:00:00'],
              dtype='datetime64[ns]', length=8881, freq='H')

In [ ]:
# Initialize empty dataframe to append entries per day 
df_day = pd.DataFrame()

# iterates over turnstiles
for i, (name, group) in enumerate(gdf):    
    # filter out only relevant columns
    df_dev = group[['Station','Line Name','SCP','C/A','Unit','Full Time','Entries','Exits']]

    # Interpolate all numerical values ('Entries' is the only numerical column in this case)
    df_dev = df_dev.sort_values(by=['Full Time'])
    df_dev = df_dev.set_index('Full Time')
    df_dev = df_dev.drop_duplicates()
    df_dev = df_dev.loc[~df_dev.index.duplicated()]
    newindex = df_dev.index.union(pd.Index(times_query))
    newindex = newindex.drop_duplicates()
    df_dev = df_dev.reindex(index = newindex)
    df_dev.sort_index()
    df_dev = df_dev.interpolate(method = 'time')
    df_dev = df_dev.loc[times_query,:]

    # Find absolute value of differences
    df_dev.sort_index()
    df_dev['Entries_diff']=df_dev['Entries'].diff().abs()
    df_dev['Exits_diff']=df_dev['Exits'].diff().abs()
    
    # Fill in missing Nan's in other columns
    def_values = {'Station':name[0],'Line Name':name[1],'SCP':name[2],'C/A':name[3],'Unit':name[4]}
    df_dev = df_dev.fillna(value = def_values)

    # Appends entries per day data for each turnstile.
    df_day = pd.concat([df_day,df_dev])
    
    if i % 100 == 0:
        print(i, *name)

0 1 AV L 00-00-00 H007 R248
100 125 ST 1 00-00-01 R174 R034
200 14 ST ACEL 01-06-01 N078 R175
300 15 ST-PROSPECT FG 00-00-02 N542 R241
400 168 ST AC1 02-00-03 N013 R035

In [13]:
# Postprocessing
df_day_new = df_day.dropna() # removes nan's due to interpolation at end cases
df_day_new = df_day_new.reset_index(drop=True)
#df_day_new = df_day_new[df_day_new['Full Time'] >= '2018-05-06'] # 2018-05-06 is 8 weeks prior to 2018-07-01 
df_day_new = df_day_new.drop(columns=['Entries','Exits'])
threshold = 15000
print('fraction excluded due to threshold criteria: ', len(df_day_new[df_day_new['Entries_diff']>=threshold])/len(df_day_new))
df_day_new = df_day_new.drop(df_day_new[df_day_new['Entries_diff']>=threshold].index)
df_day_new = df_day_new.rename(index=str, columns={"Entries_diff": "Entries_every_3hours","Exits_diff": "Exits_every_3hour"})
df_day_new

fraction excluded due to threshold criteria:  0.0011919343292975547

,Station,Line Name,SCP,C/A,Unit,Entries_every_3hours,Exits_every_3hour
0,1 AV,L,00-00-00,H007,R248,35.25,98.250000
1,1 AV,L,00-00-00,H007,R248,136.25,268.750000
2,1 AV,L,00-00-00,H007,R248,255.50,392.000000
3,1 AV,L,00-00-00,H007,R248,393.00,468.000000
4,1 AV,L,00-00-00,H007,R248,366.00,561.000000
5,1 AV,L,00-00-00,H007,R248,271.50,418.000000
6,1 AV,L,00-00-00,H007,R248,171.50,275.750000
7,1 AV,L,00-00-00,H007,R248,66.00,134.250000
8,1 AV,L,00-00-00,H007,R248,18.75,87.750000
9,1 AV,L,00-00-00,H007,R248,95.25,188.250000
10,1 AV,L,00-00-00,H007,R248,178.75,294.500000
11,1 AV,L,00-00-00,H007,R248,269.25,406.500000
12,1 AV,L,00-00-00,H007,R248,291.00,370.500000
13,1 AV,L,00-00-00,H007,R248,233.50,258.000000
14,1 AV,L,00-00-00,H007,R248,154.25,169.250000
15,1 AV,L,00-00-00,H007,R248,53.25,104.250000
16,1 AV,L,00-00-00,H007,R248,6.00,68.250000
17,1 AV,L,00-00-00,H007,R248,49.00,142.250000
18,1 AV,L,00-00-00,H007,R248,111.75,208.500000
19,1 AV,L,00-00-00,H007,R248,194.25,267.000000
20,1 AV,L,00-00-00,H007,R248,246.00,300.750000
21,1 AV,L,00-00-00,H007,R248,176.50,218.250000
22,1 AV,L,00-00-00,H007,R248,106.75,141.500000
23,1 AV,L,00-00-00,H007,R248,36.75,70.500000
24,1 AV,L,00-00-00,H007,R248,27.00,209.250000
25,1 AV,L,00-00-00,H007,R248,215.00,548.250000
26,1 AV,L,00-00-00,H007,R248,324.75,625.500000
27,1 AV,L,00-00-00,H007,R248,356.25,441.000000
28,1 AV,L,00-00-00,H007,R248,600.75,483.750000
29,1 AV,L,00-00-00,H007,R248,400.75,355.250000
...,...,...,...,...,...,...,...
14223908,ZEREGA AV,6,00-05-01,R419,R326,0.00,0.012500
14223909,ZEREGA AV,6,00-05-01,R419,R326,0.00,0.012500
14223910,ZEREGA AV,6,00-05-01,R419,R326,0.00,0.012500
14223911,ZEREGA AV,6,00-05-01,R419,R326,0.00,0.012500
14223912,ZEREGA AV,6,00-05-01,R419,R326,0.00,0.012500
14223913,ZEREGA AV,6,00-05-01,R419,R326,0.00,0.012500
14223914,ZEREGA AV,6,00-05-01,R419,R326,0.00,0.012500
14223915,ZEREGA AV,6,00-05-01,R419,R326,0.00,0.012500
14223916,ZEREGA AV,6,00-05-01,R419,R326,0.00,0.012500
14223917,ZEREGA AV,6,00-05-01,R419,R326,0.00,0.012500
14223918,ZEREGA AV,6,00-05-01,R419,R326,0.00,0.012500
14223919,ZEREGA AV,6,00-05-01,R419,R326,0.00,0.012500
14223920,ZEREGA AV,6,00-05-01,R419,R326,0.00,0.012500
14223921,ZEREGA AV,6,00-05-01,R419,R326,0.00,0.012500
14223922,ZEREGA AV,6,00-05-01,R419,R326,0.00,0.012500
14223923,ZEREGA AV,6,00-05-01,R419,R326,0.00,0.012500
14223924,ZEREGA AV,6,00-05-01,R419,R326,0.00,0.012500
14223925,ZEREGA AV,6,00-05-01,R419,R326,0.00,0.012500
14223926,ZEREGA AV,6,00-05-01,R419,R326,0.00,0.012500
14223927,ZEREGA AV,6,00-05-01,R419,R326,0.00,0.049621
14223928,ZEREGA AV,6,00-05-01,R419,R326,0.00,0.068182
14223929,ZEREGA AV,6,00-05-01,R419,R326,0.00,0.068182
14223930,ZEREGA AV,6,00-05-01,R419,R326,0.00,0.068182
14223931,ZEREGA AV,6,00-05-01,R419,R326,0.00,0.068182
14223932,ZEREGA AV,6,00-05-01,R419,R326,0.00,0.068182
14223933,ZEREGA AV,6,00-05-01,R419,R326,0.00,0.068182
14223934,ZEREGA AV,6,00-05-01,R419,R326,0.00,0.068182
14223935,ZEREGA AV,6,00-05-01,R419,R326,0.00,0.068182
14223936,ZEREGA AV,6,00-05-01,R419,R326,0.00,0.068182
14223937,ZEREGA AV,6,00-05-01,R419,R326,0.00,0.068182

In [30]:
# Save csv and pickle file
df_day_new.to_csv('Data_every_3hours.csv')
# with open('Entries_per_day.p', 'wb') as to_write:
#     pickle.dump(df_day_new, to_write)

In [18]:
whos

Variable          Type                          Data/Info
---------------------------------------------------------
NamespaceMagics   MetaHasTraits                 <class 'IPython.core.magi<...>mespace.NamespaceMagics'>
data_path         str                           /Volumes/Transcend/metis_<...>tile_Usage_Data__2018.csv
def_values        dict                          n=5
df                DataFrame                                 C/A  Unit    <...>111471 rows x 12 columns]
df_day            DataFrame                                            St<...>4648067 rows x 9 columns]
df_day_new        DataFrame                                 Station Line <...>4206984 rows x 7 columns]
df_dev            DataFrame                                            St<...>\n[2961 rows x 9 columns]
df_orig           DataFrame                                 C/A  Unit    <...>111471 rows x 11 columns]
gdf               DataFrameGroupBy              <pandas.core.groupby.grou<...>By object at 0x12566e588>
get_ipython       function                      <function get_ipython at 0x10c3fe620>
getsizeof         builtin_function_or_method    <built-in function getsizeof>
group             DataFrame                                C/A  Unit     <...>n[2148 rows x 12 columns]
i                 int                           4946
json              module                        <module 'json' from '/Use<...>hon3.6/json/__init__.py'>
name              tuple                         n=5
newindex          DatetimeIndex                 DatetimeIndex(['2017-12-2<...>, length=2980, freq=None)
np                module                        <module 'numpy' from '/Us<...>kages/numpy/__init__.py'>
pd                module                        <module 'pandas' from '/U<...>ages/pandas/__init__.py'>
pickle            module                        <module 'pickle' from '/U<...>lib/python3.6/pickle.py'>
plt               module                        <module 'matplotlib.pyplo<...>es/matplotlib/pyplot.py'>
re                module                        <module 're' from '/Users<...>ome/lib/python3.6/re.py'>
threshold         int                           15000
times_query       DatetimeIndex                 DatetimeIndex(['2017-12-2<...>, length=2961, freq='3H')
var_dic_list      function                      <function var_dic_list at 0x1150e4400>
yapf_reformat     function                      <function yapf_reformat at 0x10e1c7158>

In [28]:
del df_orig

In [29]:
whos

Variable          Type                          Data/Info
---------------------------------------------------------
NamespaceMagics   MetaHasTraits                 <class 'IPython.core.magi<...>mespace.NamespaceMagics'>
data_path         str                           /Volumes/Transcend/metis_<...>tile_Usage_Data__2018.csv
def_values        dict                          n=5
df_day_new        DataFrame                                 Station Line <...>4206984 rows x 7 columns]
gdf               DataFrameGroupBy              <pandas.core.groupby.grou<...>By object at 0x12566e588>
get_ipython       function                      <function get_ipython at 0x10c3fe620>
getsizeof         builtin_function_or_method    <built-in function getsizeof>
group             DataFrame                                C/A  Unit     <...>n[2148 rows x 12 columns]
i                 int                           4946
json              module                        <module 'json' from '/Use<...>hon3.6/json/__init__.py'>
name              tuple                         n=5
newindex          DatetimeIndex                 DatetimeIndex(['2017-12-2<...>, length=2980, freq=None)
np                module                        <module 'numpy' from '/Us<...>kages/numpy/__init__.py'>
pd                module                        <module 'pandas' from '/U<...>ages/pandas/__init__.py'>
pickle            module                        <module 'pickle' from '/U<...>lib/python3.6/pickle.py'>
plt               module                        <module 'matplotlib.pyplo<...>es/matplotlib/pyplot.py'>
re                module                        <module 're' from '/Users<...>ome/lib/python3.6/re.py'>
threshold         int                           15000
times_query       DatetimeIndex                 DatetimeIndex(['2017-12-2<...>, length=2961, freq='3H')
var_dic_list      function                      <function var_dic_list at 0x1150e4400>
yapf_reformat     function                      <function yapf_reformat at 0x10e1c7158>